// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOq2XMT_4TgnWzrdfDZIxYEaTXWSStOU',
    appId: '1:444727650212:web:b3a0502481bddb28314331',
    messagingSenderId: '444727650212',
    projectId: 'techhub-final-app',
    authDomain: 'techhub-final-app.firebaseapp.com',
    storageBucket: 'techhub-final-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfegWq0BomkrbhvEMWgppvWzwiB97aBTU',
    appId: '1:444727650212:android:2981717f4b0890d6314331',
    messagingSenderId: '444727650212',
    projectId: 'techhub-final-app',
    storageBucket: 'techhub-final-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNE_bK97CjyuSowMrFkFA9Ag5lxcjR0g',
    appId: '1:444727650212:ios:119fc8e432a785ac314331',
    messagingSenderId: '444727650212',
    projectId: 'techhub-final-app',
    storageBucket: 'techhub-final-app.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNE_bK97CjyuSowMrFkFA9Ag5lxcjR0g',
    appId: '1:444727650212:ios:119fc8e432a785ac314331',
    messagingSenderId: '444727650212',
    projectId: 'techhub-final-app',
    storageBucket: 'techhub-final-app.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQOq2XMT_4TgnWzrdfDZIxYEaTXWSStOU',
    appId: '1:444727650212:web:b6a8326f6d0d52fc314331',
    messagingSenderId: '444727650212',
    projectId: 'techhub-final-app',
    authDomain: 'techhub-final-app.firebaseapp.com',
    storageBucket: 'techhub-final-app.firebasestorage.app',
  );
}
